# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee9c8acb966c550b42beaeeae1cf48ec4757fdae3c3e927fb048fdc63f95a94c05ebd6429c670aeb9548735c1bc0f9e7f8bcf672bc78bbe384f9549e6853fec8

test:
  secret_key_base: ed524c3b2e8bd589d26c89ad781f8599fb557eede0eaede712caa089074b49e2add5cf503c060a5845ed3917b17dd8a6f51ccea40ae3fac4b1b79c0be1997762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
